export const ROOM_TYPE_ICONS = {
  bedroom:        'mdi:bed',
  master_bedroom: 'mdi:bed-king',
  bathroom:       'mdi:shower',
  toilet:         'mdi:toilet',
  kitchen:        'mdi:silverware-fork-knife',
  lounge:         'mdi:sofa',
  living_room:    'mdi:sofa',
  dining:         'mdi:food-fork-drink',
  office:         'mdi:desk',
  study:          'mdi:bookshelf',
  hall:           'mdi:door-open',
  entrance:       'mdi:door',
  landing:        'mdi:stairs',
  garage:         'mdi:garage',
  garden:         'mdi:flower',
  utility:        'mdi:washing-machine',
  conservatory:   'mdi:greenhouse',
  playroom:       'mdi:toy-brick',
  gym:            'mdi:dumbbell',
};

export const ROOM_TYPE_LABELS = {
  bedroom:        'Bedroom',
  master_bedroom: 'Master Bedroom',
  bathroom:       'Bathroom',
  toilet:         'Toilet / WC',
  kitchen:        'Kitchen',
  lounge:         'Lounge',
  living_room:    'Living Room',
  dining:         'Dining Room',
  office:         'Office',
  study:          'Study',
  hall:           'Hall',
  entrance:       'Entrance',
  landing:        'Landing',
  garage:         'Garage',
  garden:         'Garden',
  utility:        'Utility Room',
  conservatory:   'Conservatory',
  playroom:       'Playroom',
  gym:            'Gym',
};
